# Chapter 5. Getting Started with pandas

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

### Series
A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) and an associated array of data labels, called its index.

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
obj2 = pd.Series([1,2,3,4], index=['a','b','c','d'])

In [13]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [15]:
obj2['a']

a    1
b    2
c    3
d    4
dtype: int64

In [17]:
obj2[obj2>2]

c    3
d    4
dtype: int64

Another way to think about a Series is as a fixed-length, ordered dict, as it is a mapping of index values to data values. It can be used in many contexts where you might use a dict:



In [18]:
'b' in obj2

True

In [19]:
'e' in obj2 

False

In [20]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [22]:
obj3=pd.Series(sdata)

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4=pd.Series(obj3,index=states)

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

A useful Series feature for many applications is that it automatically aligns by index label in arithmetic operations:

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Both the Series object itself and its index have a name attribute, which integrates with other key areas of pandas functionality:

In [32]:
obj4.name = 'population'

In [33]:
obj4.index.name = 'state'

In [34]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

## DataFrame

A DataFrame represents a rectangular table of data and contains an ordered collection of columns, each of which can be a different value type (numeric, string, boolean, etc.). The DataFrame has both a row and column index; it can be thought of as a dict of Series all sharing the same index.
Under the hood, the data is stored as one or more two-dimensional blocks rather than a list, dict, or some other collection of one-dimensional arrays

There are many ways to construct a DataFrame, though one of the most common is from a dict of equal-length lists or NumPy arrays:

In [37]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [38]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [39]:
frame = pd.DataFrame(data)

In [40]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [41]:
pd.DataFrame(data,columns=["year","pop","state"])

year  pop   state
0  2000  1.5    Ohio
1  2001  1.7    Ohio
2  2002  3.6    Ohio
3  2001  2.4  Nevada
4  2002  2.9  Nevada
5  2003  3.2  Nevada

If you pass a column that isn’t contained in the dict, it will appear with missing values in the result:

In [45]:
frame2 = pd.DataFrame(data,columns=['year', 'state', 'pop', 'debt'],index=['a','b','c','d','e','f'])

In [46]:
frame2

year   state  pop debt
a  2000    Ohio  1.5  NaN
b  2001    Ohio  1.7  NaN
c  2002    Ohio  3.6  NaN
d  2001  Nevada  2.4  NaN
e  2002  Nevada  2.9  NaN
f  2003  Nevada  3.2  NaN

A column in a DataFrame can be retrieved as a Series either by dict-like notation or by attribute:

In [53]:
frame2['pop']

a    1.5
b    1.7
c    3.6
d    2.4
e    2.9
f    3.2
Name: pop, dtype: float64

In [48]:
frame2.year

a    2000
b    2001
c    2002
d    2001
e    2002
f    2003
Name: year, dtype: int64

Rows can also be retrieved by position or name with the special loc attribute (much more on this later):

In [55]:
frame2.loc['c']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: c, dtype: object

Columns can be modified by assignment. For example, the empty 'debt' column could be assigned a scalar value or an array of values:

In [57]:
frame2['debt'] = 16.5

In [58]:
frame2

year   state  pop  debt
a  2000    Ohio  1.5  16.5
b  2001    Ohio  1.7  16.5
c  2002    Ohio  3.6  16.5
d  2001  Nevada  2.4  16.5
e  2002  Nevada  2.9  16.5
f  2003  Nevada  3.2  16.5

If you assign a Series, its labels will be realigned exactly to the DataFrame’s index, inserting missing values in any holes:

In [60]:
val = pd.Series(['a','b','c'],index = ['a','b','c'])

Assigning a column that doesn’t exist will create a new column. The del keyword will delete columns as with a dict.

In [66]:
frame2['debt1']=val

In [67]:
frame2

year   state  pop debt debt1
a  2000    Ohio  1.5    a     a
b  2001    Ohio  1.7    b     b
c  2002    Ohio  3.6    c     c
d  2001  Nevada  2.4  NaN   NaN
e  2002  Nevada  2.9  NaN   NaN
f  2003  Nevada  3.2  NaN   NaN

The del method can then be used to remove this column:

In [69]:
del frame2['debt1']

In [70]:
frame2

year   state  pop debt
a  2000    Ohio  1.5    a
b  2001    Ohio  1.7    b
c  2002    Ohio  3.6    c
d  2001  Nevada  2.4  NaN
e  2002  Nevada  2.9  NaN
f  2003  Nevada  3.2  NaN

If the nested dict is passed to the DataFrame, pandas will interpret the outer dict keys as the columns and the inner keys as the row indices:

In [79]:
pop = {'Nevada': {2002: 2.4, 2001: 2.9},
 		'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [81]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

You can transpose the DataFrame (swap rows and columns) with similar syntax to a NumPy array:

In [78]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

The keys in the inner dicts are combined and sorted to form the index in the result. This isn’t true if an explicit index is specified:

In [84]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.9   1.7
2002     2.4   3.6
2003     NaN   NaN

Dicts of Series are treated in much the same way:

In [86]:
frame3['Ohio'][:-1]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [87]:
frame3['Nevada'][:2]

2001    2.4
2002    2.9
Name: Nevada, dtype: float64

In [88]:
pdata = {'Ohio': frame3['Ohio'][:-1],
	  'Nevada': frame3['Nevada'][:2]}

In [89]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

As with Series, the values attribute returns the data contained in the DataFrame as a two-dimensional ndarray:

In [90]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [91]:
frame2.values

array([[2000, 'Ohio', 1.5, 'a'],
       [2001, 'Ohio', 1.7, 'b'],
       [2002, 'Ohio', 3.6, 'c'],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, nan],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

pandas’s Index objects are responsible for holding the axis labels and other metadata (like the axis name or names).

Any array or other sequence of labels you use when constructing a Series or DataFrame is internally converted to an Index:

In [92]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [93]:
index = obj.index

In [94]:
index

Index(['a', 'b', 'c'], dtype='object')

Index objects are immutable and thus can’t be modified by the user:

In [ ]:
index[1] = 'd' #TypeError

In [96]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In addition to being array-like, an Index also behaves like a fixed-size set:

In [97]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [98]:
'Ohio' in frame3.columns

True

Unlike Python sets, a pandas Index can contain duplicate labels, Selections with duplicate labels will select all occurrences of that label.

In [99]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Essential Functionality

### Reindexing

to create a new object with the data conformed to a new index

In [101]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [102]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [103]:
obj.reindex(['a', 'b', 'c', 'd', 'e'])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

using a method such as ffill, which forward-fills the values:

In [105]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [106]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [107]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

With DataFrame, reindex can alter either the (row) index, columns, or both. When passed only a sequence, it reindexes the rows in the result:

In [108]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [109]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [112]:
frame.reindex(['a','b','c','d'])

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

The columns can be reindexed with the columns keyword:

In [115]:
frame.reindex(columns=['Ohio','Pachora','California'])

Ohio  Pachora  California
a     0      NaN           2
c     3      NaN           5
d     6      NaN           8

In [126]:
states = ['Ohio','Texas','California']
frame.loc[['a','c','d'],states]

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [127]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

Dropping Entries from an Axis

In [128]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [129]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [130]:
obj.drop('c')

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering
Series indexing (obj[...]) works analogously to NumPy array indexing, except you can use the Series’s index values instead of only integers. Here are some examples of this:

In [131]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [132]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [136]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [137]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [139]:
obj['b':'c'] # Slicing with labels behaves differently than normal Python slicing in that the endpoint is inclusive:

b    1.0
c    2.0
dtype: float64

In [140]:
obj['b':'c'] = 5

In [141]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [143]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [144]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [145]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [147]:
data[['three', 'one']] #I think this we can not do in case of NumPy Array

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [148]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

### SELECTION WITH LOC AND ILOC

They enable you to select a subset of the rows and columns from a DataFrame with NumPy-like notation using either axis labels (loc) or integers (iloc).

In [150]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

We’ll then perform some similar selections with integers using iloc:

In [152]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [153]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [154]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

In [156]:
ser = pd.Series(np.arange(3.))

In [159]:
ser[-1]

KeyError: -1

On the other hand, with a non-integer index, there is no potential for ambiguity:

In [162]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [163]:
ser2[-1]

2.0

### Arithmetic and Data Alignment


In [172]:
s1= pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [173]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [174]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

1. If the lables are not matching then the result will conain NaN value
2. If the labels are missing then it will contain all null

Using the add method on df1, I pass df2 and an argument to fill_value:

In [176]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),columns=list('abcd'))

In [177]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list('abcde'))

In [178]:
df2.loc[1, 'b'] = np.nan

In [179]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [180]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [181]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [182]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

### OPERATIONS BETWEEN DATAFRAME AND SERIES

In [185]:
arr = np.arange(12.).reshape((3, 4))

When we subtract arr[0] from arr, the subtraction is performed once for each row. This is referred to as broadcasting and is explained in more detail as it relates to general NumPy arrays in Appendix A. Operations between a DataFrame and a Series are similar:

In [184]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

### Function Application and Mapping

NumPy ufuncs (element-wise array methods) also work with pandas objects:

In [187]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [188]:
frame

b         d         e
Utah    0.309933 -0.904885  1.205449
Ohio    1.068104 -0.221045  0.124429
Texas   0.953091  0.476973 -0.591198
Oregon -0.829790  2.059571 -0.012395

In [189]:
np.abs(frame)

b         d         e
Utah    0.309933  0.904885  1.205449
Ohio    1.068104  0.221045  0.124429
Texas   0.953091  0.476973  0.591198
Oregon  0.829790  2.059571  0.012395

Another frequent operation is applying a function on one-dimensional arrays to each column or row. DataFrame’s apply method does exactly this:

In [190]:
f = lambda x: x.max() - x.min()

In [191]:
frame.apply(f)

b    1.897894
d    2.964456
e    1.796647
dtype: float64

If you pass axis='columns' to apply, the function will be invoked once per row instead:

In [192]:
frame.apply(f, axis='columns')

Utah      2.110334
Ohio      1.289149
Texas     1.544289
Oregon    2.889361
dtype: float64

Many of the most common array statistics (like sum and mean) are DataFrame methods, so using apply is not necessary.
The function passed to apply need not return a scalar value; it can also return a Series with multiple values:

In [193]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [194]:
frame.apply(f)

b         d         e
min -0.829790 -0.904885 -0.591198
max  1.068104  2.059571  1.205449

Element-wise Python functions can be used, too. Suppose you wanted to compute a formatted string from each floating-point value in frame. You can do this with applymap:

In [196]:
format = lambda x: '%.2f' % x

In [197]:
frame.applymap(format)

b      d      e
Utah     0.31  -0.90   1.21
Ohio     1.07  -0.22   0.12
Texas    0.95   0.48  -0.59
Oregon  -0.83   2.06  -0.01

The reason for the name applymap is that Series has a map method for applying an element-wise function:

In [199]:
frame['e'].map(format)

Utah       1.21
Ohio       0.12
Texas     -0.59
Oregon    -0.01
Name: e, dtype: object

### Sorting and Ranking

Sorting a dataset by some criterion is another important built-in operation. To sort lexicographically by row or column index, use the sort_index method, which returns a new, sorted object:

In [ ]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [200]:
obj.sort_index()

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

With a DataFrame, you can sort by index on either axis:

In [201]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),index=['three', 'one'],columns=['d', 'a', 'b', 'c'])

In [202]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [203]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [204]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [211]:
frame.sort_values(by="a")

d  a  b  c
three  0  1  2  3
one    4  5  6  7

Ranking assigns ranks from one through the number of valid data points in an array. The rank methods for Series and DataFrame are the place to look; by default rank breaks ties by assigning each group the mean rank:

In [212]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [213]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

Ranks can also be assigned according to the order in which they’re observed in the data:

In [215]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

### Summarizing and Computing Descriptive Statistics

In [216]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=['a', 'b', 'c', 'd'],columns=['one', 'two'])

In [217]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

Calling DataFrame’s sum method returns a Series containing column sums:

In [218]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [219]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [220]:
df.cumsum() # Cumulative Sum

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [221]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

On non-numeric data, describe produces alternative summary statistics:

In [223]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [224]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [225]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object